### ISSUE TITLE
Cannot build: undefined reference to `QuantizeBuffer'

### ISSUE THREAD

**Issue by cezio** [rainycape/magick#21]
I'm trying to install this package, but got this build error. I saw in current issues that there is a problem with compilation with giflib 5.x, but I've verified my local installation, and I'm pretty sure I'm using giflib.4.3. 

```
cezio@gburek [linux_amd64 $]>go get github.com/rainycape/magick 
# github.com/rainycape/magick
/tmp/.private/cezio/go-build336908180/github.com/rainycape/magick/_obj/gif.o: In function `gif_encode':
../../src/github.com/rainycape/magick/gif.c:325: undefined reference to `QuantizeBuffer'
collect2: error: ld returned 1 exit status
```

```
gburek cezio # emerge -s giflib
Searching...    
[ Results for search key : giflib ]
[ Applications found : 1 ]

*  media-libs/giflib
      Latest version available: 4.2.3-r1
      Latest version installed: 4.2.3-r1
      Size of files: 548 KiB
      Homepage:      http://sourceforge.net/projects/giflib/
      Description:   Library to handle, display and manipulate GIF images
      License:       MIT

```
Go version:
```
go version go1.3.1 linux/amd64
```

Any hints, ideas?

**Comment by rainycape** [comment]
@cezio giflib 5 added QuantizeBuffer back, and was released almost 4 years ago. I think the best solution is to just use either giflib >= 5 or giflib < 4.2. The only other solution is just copying the code for QuantizeBuffer into magick, but that's just ugly.

Also, most distributions have just skipped giflib 4.2 (e.g. Debian stable has 4.1, unstable has 5.1). In your specific case, these days Gentoo seems to be doing exactly the same https://packages.gentoo.org/packages/media-libs/giflib.
