### ISSUE TITLE
QuantizeBuffer doesn't exist in newer versions of giflib

### ISSUE THREAD

**Issue by jeffrafter** [rainycape/magick#36]
By default when installing giflib via homebrew like `brew install giflib` installs version 4.2.3 (currently) on OSX Yosemite / El Capitan. When you `brew install graphicsmagick` it links against this version. Using `go get` for a project containing rainycape will result in the following error:

```
# github.com/rainycape/magick
rainycape/magick/gif.c:312:9: warning: implicit declaration of function 'QuantizeBuffer' is invalid in C99 [-Wimplicit-function-declaration]
rainycape/magick/gif.c:25:31: note: expanded from macro 'GifQuantizeBuffer'
# github.com/rainycape/magick
Undefined symbols for architecture x86_64:
  "_QuantizeBuffer", referenced from:
      _gif_encode in gif.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This is because `QuantizeBuffer` no longer exists in 4.2.x (and beyond). This looks like it has been solved here https://github.com/etix/magick/commit/31194bfcaa9948ba99bd1f6ccbdcc10f714a0251

For anyone stuck on this issue, a temporary workaround is to use the 4.1.x branch of giflib (which is out of date):

```
brew uninstall giflib
brew uninstall graphicsmagick
brew install https://raw.githubusercontent.com/Homebrew/homebrew/ff9ec519666c16dd3eabf77861d986d7a1cd3b71/Library/Formula/giflib.rb
brew install graphicsmagick
```

**Comment by rainycape** [comment]
@jeffrafter QuantizeBuffer wasn't available in a few intermediate releases of giflib 4, but it's back in giflib 5.0. Unfortunately, supporting the 4.x releases which don't have QuantizeBuffer would require adding a lot of code for almost no benefit. As you have found, the easiest workaround is using either giflib 4.1 or giflib 5.0.

**Comment by marktheunissen** [comment]
This worked for me:

```
brew install homebrew/versions/giflib5
export CGO_LDFLAGS="-L/usr/local/opt/giflib5/lib"
export CGO_CPPFLAGS="-I/usr/local/opt/giflib5/include"
go get github.com/rainycape/magick
```
